.gitlab-ci.yml

also fix SSH_PRIVATE_KEY
fixes #65

start with an image that has hugo pre-installed

---

website/scripts/populate-releases.py

handles the older python3 version on the build:servlet4 image.
fixes #65

do not use f-strings

---

.gitlab-ci.yml

switch to our own image and remove -i option (required on mac) from sed

---

.gitlab-ci.yml

saw in the last build the html was going to the console vs inplace.
fixes #65

re-add the -i for inplace modifications by sed

---

.github/PULL_REQUEST_TEMPLATE.MD

Fixes the incorrect link in the existing PR template, and adds a header requesting _testing steps_ for verifying that the PR works correctly.
Fixes #92 
Windows 10 using Eclipse 2019-12.

i92: updated PR Template link, added request for testing steps.

---

projects/WTI-API/buildWTI.xml

The last PR broke building on the pipeline.  This fixes that.

fix another Linx vs Unix.

---

createAPIJar.xml
createVERSIONandJar.xml

update from jdk 1.7 to jdk 1.8

---

build.xml
website/scripts/populate-releases.py

also remove an extra s from a var name.
fixes #153

bump version to 9.7.0

---

website/scripts/populate-releases.py

properly copy-n-pasted the right variable name.
fixes #158
This will need to be cherry-picked over to the master branch.

remove the s and add the underscore

---

README.MD
website/content/_index.md
website/content/all-builds.md
website/content/current.md

I saw a very small typo on some pages.

Fix small typo in readme and on pages

---

build.xml

fixes #156.  
From #156 
Change distribution build version number from 9.7 to 9.8,
before pc2-9.7build-<buildnumber>.zip
after pc2-9.8build-<buildnumber>.zip
please merge this after the 9.7.0 (#153)

version bump to 9.8.0

---

src/edu/csus/ecs/pc2/ui/board/ScoreboardView.java

Fixed a bug generating html when Refresh button selected/used.
#217 
all.
**To Reproduce**: please describe, in order, the steps to reproduce the behavior:
- start server
- start admin
- generate 1 scoreboard account
- start scoreboard 1
- select the Refresh button
- remove all files under html/ and public_html/
- select the Refresh button
Expected
new html files under html/ and public_html/ directories

I217: Fixed refresh button on scoreboard UI

---

src/edu/csus/ecs/pc2/core/report/GroupComparatorById.java
src/edu/csus/ecs/pc2/core/report/ProblemGroupAssignmentReport.java
src/edu/csus/ecs/pc2/core/report/Reports.java
src/edu/csus/ecs/pc2/ui/ReportPane.java
test/edu/csus/ecs/pc2/core/report/ProblemGroupAssignmentReportTest.java
test/edu/csus/ecs/pc2/core/report/ReportsTest.java

Added 
Added report to Report list on Reports Pane and Reports command
line, aka pc2reports.
#219 
all.
- pc2reset if necessary to clear pc2 config
-- run server, load from sample
```
bin\pc2server --login s --contestpassword foo  --load samps\contests\valtest
```
- on Reports tab select Problem Group Assignment report
- View report
Expected output.   
Compare problem group assignments in problem.yaml with report output.
```
--- 12 groups ---
12542    - Hawaii - BYUH, Laie, Oahu D1               ; assigned to 4 problems [A, B, E, F]
12543    - Northeast - EWU, Cheney/Spokane D1         ; assigned to 4 problems [A, B, E, F]
12544    - Northwest - George Fox University D1       ; assigned to 0 problems []
12545    - Canada - University of British Columbia D1 ; assigned to 4 problems [A, B, …
```

I 219 add problem group assignments report

---

src/edu/csus/ecs/pc2/ui/EditRunPane.java

Provide a way to change a run status to any run status in Edit Run
Changed status value (label/immutable) to combo-box on Admin Edit Run.
#223
Java version 1.8.0_121
OS: Windows 10 10.0 (amd64)
tl;dr - add runs, edit run state, verify state changed on admin and judge.
Submit runs
1. start server with sample contest, ex. --load valtest.
2. start admin
1. - generate 10 team accounts starting at team 1 (first team from CDP is team 101)
1. - start clock
1. start a judge, view All Runs tab to view status change
1. start a team then submit runs
Edit run
1. On admin -> Run Contest -> Runs tab
1. edit run, change status
Verify
1. verify status has changed in admin Run grid.
1. verify status has changed in judge All Runs grid.
Expected
Run status changed on admin and judge (aka everywhere)

i223: now admin can change run status to any value (using Edit Run)

---

projects/WTI-API/scripts/wtizip
projects/WTI-API/scripts/wtizip.bat
projects/WTI-API/src/main/edu/csus/ecs/pc2/wti/core/archive/ZipWTI.java

Implemented wtizip, added scripts and ZipWTI class 
#198 
all.
To create a zip archive (nearly identical in use and contents of pc2zip, only the names have changed :) )
1.  run wtizip in WTI directory where pc2v9.ini found (WTI jake directory)
Unix:
```
bin/wtizip
```
DOS/Windows
```
bin\wtizip
```
This will pack files and create a .zip file under archive/
Example
```
C> bin\wtizip
Mon Mar 22 11:36:24 PDT 2021 Creating archive\202103221836-pc2wtiarchive.zip
Mon Mar 22 11:36:24 PDT 2021 Adding logs\pc2.startup.1616437446002-0.log
Mon Mar 22 11:36:24 PDT 2021 Adding logs\pc2.startup.1616437477661-0.log
Mon Mar 22 11:36:24 PDT 2021 Adding logs\pc2.startup.1616437477661-0.log.lck
Mon Mar 22 11:36:24 PDT 2021 Adding logs\pc2.startup.1616437478237-0.log
Mon Mar 22 11:36:24 PDT 2021 Adding …
```

i198: added WTI zip programs

---

src/edu/csus/ecs/pc2/shadow/RemoteEventFeedMonitor.java

As described in https://github.com/pc2ccs/pc2v9/issues/240, there are times when it is important to have more than one "Shadow Controller" running.  However it is also important that additional Shadow Controllers not be allowed to forward submissions from the Remote CCS to the PC2 server.  This commit/PR adds a check to the RemoteEventFeedMonitor to see what account a Shadow client is currently logged in with; only Feeder1 is allowed to actually forward (submit) a submission to the PC2 server.
This is a _partial_ fix for Issue #240; however, it does not provide a fully robust solution.  See the comments in Issue #240 for further details regarding a complete fix.
Windows 10, Java 8.1_271
- Start a PC2 Server, loading a CDP for a contest which is already configured into a remote CCS. For …

i240: only allow RemoteEventFeedMonitor to submit when Feeder1. Detail:

---

.gitlab-ci.yml

i302: fixing build for node manager

---

test/edu/csus/ecs/pc2/core/util/AbstractTestCase.java
test/edu/csus/ecs/pc2/services/core/ScoreboardJsonTest.java

change fastJUnitTesting = true
remove debug 22 for scorboard JSON

i302: change to fast JUnit testing

---

.gitlab-ci.yml
projects/WTI-UI/package.json

revert/change   "core-js": "~3.4.0", to  "core-js": "^2.5.4",

i302: add archiveSkipTests, revert package.json

---

.gitlab-ci.yml
test/edu/csus/ecs/pc2/core/util/AbstractTestCase.java

I302 change version to stable v12

---

src/edu/csus/ecs/pc2/core/scoring/DefaultScoringAlgorithm.java
src/edu/csus/ecs/pc2/core/scoring/StandingsRecord.java
test/edu/csus/ecs/pc2/core/scoring/DefaultScoringAlgorithmTest.java

This depends on the group displayName ending with D\d+
fixes #315
btw, also added an overalRank (== rank)

Add some divisionRank support

---

samps/contests/sumitMTC/config/sumit/problem.yaml
src/edu/csus/ecs/pc2/core/execute/Executable.java
src/edu/csus/ecs/pc2/core/export/ExportYAML.java
src/edu/csus/ecs/pc2/core/report/ProblemsReport.java
src/edu/csus/ecs/pc2/imports/ccs/ContestSnakeYAMLLoader.java
src/edu/csus/ecs/pc2/imports/ccs/IContestLoader.java
test/edu/csus/ecs/pc2/imports/ccs/ContestSnakeYAMLLoaderTest.java

Creates yaml with mem limit and sandbox variables:  memory-limit-in-Meg, sandbox-type,
sandbox-command-line, sandbox-program-name
\# in problem.yaml  (added example in samps/contests/sumitMTC/config/sumit/problem.yaml)
limits:
timeout: 10
memory-limit-in-Meg: 2048
sandbox-type: NONE
sandbox-command-line: '{:sandbox} {:memlimit} {:timelimit}'
sandbox-program-name: 'pc2sandbox.sh
Loads yaml with mem limit and sandbox variables
In Executable substitute mem limit and sandbox variables
Each of these are substituted based on the run's problem
{:memlimit} for int getMemoryLimitMB() 
{:sandboxcommandline} for String getSandboxCmdLine() 
{:sandboxprogramname} for String getSandboxProgramName() 
In Problems report new variables are now present.
partial #295
Microsoft Windows [Version …

I 295 new executable and yaml load

---

src/edu/csus/ecs/pc2/core/Constants.java
src/edu/csus/ecs/pc2/core/execute/Executable.java
src/edu/csus/ecs/pc2/core/model/Problem.java
src/edu/csus/ecs/pc2/sandbox/pc2InternalSandbox.sh

Adds code to Executable to check for and invoke a PC2 Internal Sandbox.  
Partial for #295 
Win 10.1, Java 1.8_201, Eclipse Version: 2019-12 (4.14.0)
Partial development; no tests available yet.

I 295 develop work

---

test/edu/csus/ecs/pc2/imports/ccs/ContestSnakeYAMLLoaderTest.java

sumitMTC fixed to SumitMTC
fixed unit test fixes build job
#364

i364: fix typo in unit test

---

samps/uiname.properties
src/edu/csus/ecs/pc2/ui/admin/AdministratorLegacyView.java
src/edu/csus/ecs/pc2/ui/board/ScoreboardLegacyView.java
src/edu/csus/ecs/pc2/ui/judge/JudgeLegacyView.java
src/edu/csus/ecs/pc2/ui/team/TeamLegacyView.java

Adds Legacy View classes for Admin, Judge, Scoreboard and Team
and examples/instructions in samps/uiname.properties about how
to select/load the Legacy views.
#384
Microsoft Windows [Version 10.0.19044.1645]
Summary: Start server, update uinames.properties, start module UIs
Since the UI's are identical, must check log to determine which UI class was loaded/used.
1. Start server with tenprobs sample (creates needed accounts).
2.  copy samps/uiname.properties into same directory as pc2v9.ini
3.  edit uinames.properties, un-comment all lines with login names as name
Before:
\# administrator1=edu.csus.ecs.pc2.ui.admin.AdministratorLegacyView
After: …

I 384 create legacy view classes

---

src/edu/csus/ecs/pc2/shadow/RemoteEventFeedMonitor.java

Skips event feed delay for events of type "runs".
Partial attempt to fix #267

i267: additional Q&D patch:  skip delay on "event type == runs".

---

src/edu/csus/ecs/pc2/shadow/ShadowController.java

i397: add stack trace to log

---

.gitlab-ci.yml

remove reference to CSUS

---

.github/workflows/ci.yml

per https://docs.github.com/en/actions/learn-github-actions/expressions
fixes #507

change or to ||

---

.github/workflows/ci.yml
build.xml
projects/EWTeam/build.xml
projects/WTI-API/packageWTI.xml

revert VERSION building to .gitlab-ci.yaml version

---

.github/workflows/ci.yml

fixes from johnb.

---

.github/workflows/ci.yml

strip ~ foo from tag_name

---

website/scripts/populate-releases.py

pass the token

---

.github/workflows/ci.yml
website/data/pc2.yaml

fixes #507
still looking into the pc&sup2;  issue.

fix pre-release

---

.github/workflows/ci.yml

remove extra dash

---

.github/workflows/ci.yml

move the dash, not remove

---

build.xml
createAPIJar.xml
createVERSIONandJar.xml

fixes #525
to test, install a newer jdk 17+ and run 
ant
it should work with this fix, before my fix it would have failed on the first javac.

javac change bootclasspath to classpath

---

.github/PULL_REQUEST_TEMPLATE.MD

Updates the PC2v9 PR template.
Fixes #684.
Windows 10.1
- Submit a new Issue.
- Submit a PR for that issue.
Verify that the PR template indicates that the words "Fixes" or "Closed" should be included in the **Issue which the PR addresses** section.

i682: update PR template to make it clearer how "Fixes" section works.

---

src/edu/csus/ecs/pc2/core/Constants.java
src/edu/csus/ecs/pc2/ui/PluginLoadPane.java
src/edu/csus/ecs/pc2/ui/QuickJudgePane.java
src/edu/csus/ecs/pc2/ui/admin/AdministratorView.java

Adds Quick Judge Pane on Admin under Run Contests
Added to UI Plugin list
Fixes #723 
See #723 for Pane components
Setup 
load and start server, --load tenprobs (contest time starts automatically, with 80 teams)
submit 12 runs as different teams
Test 1 - Change 6 runs to Yes
Note the run count in the top right corner, it will
change as runs are judged/"rejudged"/filtered
Run Contest -> Quick Judge 
- select 6 runs
- change judgement (pull down) to Yes
- click Submit
- click Yes
View judged runs
- uncheck View Unjudged only, 
see run count 
- check View Unjudged only, 
confirm run count change with fewer …

i723: Added Quick Judge Pane.   Fixes 723

---

data/xsl/full.xsl
data/xsl/fullnums.xsl
data/xsl/index.xsl
data/xsl/sumatt.xsl
data/xsl/summary.xsl
data/xsl/sumtime.xsl
samps/web/xsl/group1.xsl
samps/web/xsl/groupN.xsl
samps/web/xsl/index.xsl
samps/web/xsl/index1.xsl
samps/web/xsl/index2.xsl
samps/web/xsl/wf.groupN.xsl
samps/web/xsl/wf.index.xsl
samps/web/xsl/wf.standings.xsl

to https://pc2ccs.github.io/
also add the index1/2.xsl that we use at PacNW contest.
fixes #330

update old references to (www|pc2).ecs.csus.edu

---

src/edu/csus/ecs/pc2/ui/ClarificationsTablePane.java

fixes #493
to test:
./bin/pc2reset
./bin/pc2server --login s1 --contestpassword contest --load samps/contests/sumitMTC/config
./bin/pc2admin --login r
start the contest
./bin/pc2team --login 1
submit a general clar and a sumit clar
./bin/pc2judge --login j10
play with answering either clar.

remember when we are already answering a clar

---

src/edu/csus/ecs/pc2/ui/JSerializFilePicker.java
src/edu/csus/ecs/pc2/ui/SubmitRunPane.java
src/edu/csus/ecs/pc2/ui/TestResultsPane.java

Changed the texts for a few JRadioButton, pickFileButton from 'Select' to 'Select...'
Fixes #820 
Start Server, Admin and Team and check for any buttons which shows 'Select...' and none shows 'Select'

I820: Changed JRadioButton, pickFileButton text from 'Select' to 'Select...'

---

src/edu/csus/ecs/pc2/ui/SelectJudgementFrame.java

Add an explicit check for a client of type **SERVER** when setting the contest and controller in `SelectJudgementFrame`. 
This allows a server client to initialize a **RunsTablePane** or **RunsPane** without generating an NPE.
Fixes #933 
Windows 11
jdk1.8.0_321
1) Add a **RunsTablePane** to the server GUI client.  (Details of how to do this are left to the reader).
2) Start the server.
3) Navigate to the **Runs** tab.
4) Note that there are no NPE exceptions on the console or in the logs related to **RunsTablePane**.

i933 Explicitly check for server when initializing for RunsTables
